# Generated by Django 5.2.1 on 2025-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Ficção', 'Ficção'), ('Biografia', 'Biografia'), ('Técnico', 'Técnico')], max_length=50)),
                ('capa', models.ImageField(upload_to='capas/')),
            ],
        ),
    ]
