# Generated by Django 5.2.1 on 2025-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='local',
            field=models.CharField(choices=[('Kindle', 'Kindle'), ('Play Livros', 'Play Livros'), ('Físico', 'Físico')], default='Físico', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
