# Generated by Django 5.2.1 on 2025-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_remove_livro_categoria_remove_livro_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='nota',
            field=models.DecimalField(blank=True, choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], decimal_places=1, max_digits=2, null=True),
        ),
    ]
