# Generated by Django 5.2.1 on 2025-05-17 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
