# Generated by Django 5.2.1 on 2025-05-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_capa_alter_livro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
