# Generated by Django 5.2.1 on 2025-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livro_lido'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='onde_comprar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
