# Generated by Django 5.2.1 on 2025-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_livro_onde_comprar_livro_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='onde_comprar_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='onde_comprar_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
