# Generated by Django 5.2.1 on 2025-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_livro_onde_comprar_link_livro_onde_comprar_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='local',
            field=models.CharField(choices=[('Kindle', 'Kindle'), ('Play Livros', 'Play Livros'), ('Físico', 'Físico'), ('Lista de Desejos', 'Lista de Desejos')], max_length=20),
        ),
    ]
