# Generated by Django 5.2.1 on 2025-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_livro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='url_capa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='onde_comprar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
