# Generated by Django 5.2.1 on 2025-07-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_livro_url_capa_alter_livro_onde_comprar_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='usuario',
        ),
    ]
