# Generated by Django 5.2.1 on 2025-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_remove_livro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='onde_comprar',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='onde_comprar_link',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='onde_comprar_nome',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='preco',
        ),
        migrations.AlterField(
            model_name='livro',
            name='local',
            field=models.CharField(choices=[('Kindle', 'Kindle'), ('Play Livros', 'Play Livros'), ('Físico', 'Físico')], max_length=20),
        ),
    ]
